export { default as Login } from "./Login"
export { default as Main } from "./Main"
export { default as Cadastro } from "./Cadastro"
export { default as Banda } from "./Banda"
export { default as BandaStore } from "./Banda/store"
export { default as Musica } from "./Musica"
export { default as MusicaStore } from "./Musica/store"